title = "Reilly Tucker Siemens"
base_url = "https://tuckersiemens.com"
generate_categories_pages = false
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra.author]
name = "Reilly Tucker Siemens"
